---
- hosts: localhost
  become: true
  vars:
     namespace: prudential
  tasks:
    - name: Git checkout application code
      ansible.builtin.git:
        repo: 'https://github.com/sabamoazzam28/prudential.git'
        dest: /app
    - name: Install kubectl
      shell: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - name: Granting exec permission 
      file:
        path: ./kubectl
        mode: '775
    - name: Moving executable to bin folder
      command: mv kubectl /usr/local/bin/
    - name: Build Dockerfile
      shell: docker build -t myapp/javaimg
    - name: Create namespace
      command: kubectl create ns prudential
      become_user: ubuntu
      ignore_errors: yes
    - name: Scala Java app in Kubernetes cluster 
      shell: kubectl apply -f deployment.yaml -n {{ namespace }}
      ignore_errors: yes
    - name: Create service for app
      shell: kubectl apply -f service.yml -n {{ namespace }}
      ignore_errors: yes