#Copy application code from Jenkins slave node to container and run mvn cmd to get required jar file
FROM maven:3.5.2-jdk-8-alpine AS MAVEN_TOOL
COPY . /tmp/
WORKDIR /tmp/
RUN mvn install

#Use generated jar file and run java application
FROM openjdk:8-jdk-alpine
COPY --from=MAVEN_TOOL /tmp/target/*.jar /target/*.jar
ARG JAR_FILE=/tmp/target/*.jar
COPY ${JAR_FILE} app.jar
EXPOSE 8080-8080
ENTRYPOINT ["java","-jar","/app.jar"]

stage('Clone git') {
                          steps {sh 'mkdir repo1'
                                 sh 'cd repo1'
                                 dir ('repo1') {
                                 git ([url : 'https://github.../repo1.git', branch : 'develop', credentialsId : '***'])}

                                 sh 'mkdir repo2'
                                 sh 'cd repo2'
                                 dir ('repo2') {
                                 git ([url : 'https://github.../repo2.git', branch : 'develop', credentialsId : '***'])}
                      }
                  }

 stage('Build Docker') {
                      steps {sh 'cd ..'
                             sh 'docker build -t myimage .'
                             sh 'docker run myimage'
                      }